name: Health Check & Notification

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  check-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Health Check - Run health check on the application
        id: health_check
        run: |
          HEALTH_CHECK_URL="http://13.53.124.28:3000/health"
          response=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
          echo "Response code: $response"
          if [[ "$response" -ne 200 ]]; then
            echo "Health check failed!"
            exit 1
          else
            echo "Health check passed."
          fi

      - name: Notify Dynatrace (failure)
        if: failure()
        env:
          DT_URL: ${{ secrets.DT_URL }}
          DT_TOKEN: ${{ secrets.DT_TOKEN }}
        run: |
          curl -X POST "$DT_URL/api/v2/events/ingest" \
            -H "Authorization: Api-Token $DT_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "eventType": "CUSTOM_ALERT",
              "title": "Health Check Failed",
              "description": "The application health check failed.",
              "properties": {
                "source": "GitHub Actions",
                "status": "failure"
              }
            }'

      - name: Notify Symphony (failure)
        if: failure()
        env:
          SYMPHONY_WEBHOOK_URL: ${{ secrets.SYMPHONY_WEBHOOK_URL }}
        run: |
          curl -X POST "$SYMPHONY_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "ALERT: Health Check failed for the application. Immediate attention required!"
            }'
